-- =============================================================================
-- BRONZE: AECB (UAE Credit Bureau)
-- =============================================================================
-- Source pattern : Async, file-based. Triggered per application; AECB processes
--                   the request and drops a response file on SFTP some time
--                   later (minutes to hours). Picked up by the ~5-minute Bronze
--                   ingestion cadence as files land — NOT a fixed nightly bulk
--                   pull of the full customer base.
-- Match key       : Emirates ID
-- Write pattern   : Append-only. Never updated or overwritten.
-- =============================================================================

CREATE TABLE bronze.aecb (
    bronze_id                STRING      COMMENT 'Surrogate key for this raw record (UUID)',
    source_system            STRING      COMMENT 'Always ''aecb''',
    source_event_id          STRING      COMMENT 'AECB''s own reference for this report (filename + row, or report ID)',
    application_id           STRING      COMMENT 'Correlation ID generated by the decision service before the outbound request',
    internal_uuid            STRING      COMMENT 'Canonical customer identifier, known before the request was made',
    received_at              TIMESTAMP   COMMENT 'When we received/wrote this record',
    source_generated_at      TIMESTAMP   COMMENT 'Timestamp AECB reports inside the report payload',
    ingest_date              DATE        COMMENT 'Partition column, derived from received_at',
    schema_version           STRING      COMMENT 'AECB report format version',
    raw_payload              STRING      COMMENT 'Entire original XML payload, untouched, stored as text'
)
PARTITIONED BY (ingest_date)
STORED AS PARQUET
LOCATION 's3://mal-lakehouse/bronze/aecb/'
TBLPROPERTIES ('write.format.default' = 'parquet');

-- Notes:
--   * raw_payload retains the XML exactly as received. It is parsed into typed
--     columns only in Silver (silver.aecb_conformed) — Bronze never interprets it.
--   * No UPDATE or DELETE operations are permitted against this table. Corrections
--     from AECB arrive as new rows, never edits to existing ones.
--   * application_id is metadata WE attach on arrival, matched back to the
--     outbound request via our own request log — AECB does not echo it.
