-- =============================================================================
-- BRONZE: Fraud Detection Provider
-- =============================================================================
-- Source pattern : Synchronous, real-time REST API call made inline as part of
--                   the application flow. Response returns in sub-second time.
--                   Bronze write is decoupled via a queue so persistence never
--                   blocks the live decision call.
-- Match key       : Phone + email
-- Write pattern   : Append-only. Never updated or overwritten.
-- =============================================================================

CREATE TABLE bronze.fraud (
    bronze_id               STRING      COMMENT 'Surrogate key for this raw record (UUID)',
    source_system           STRING      COMMENT 'Always ''fraud''',
    source_event_id         STRING      COMMENT 'Fraud provider''s request_id for this score',
    application_id          STRING      COMMENT 'Correlation ID generated by the decision service before the outbound call',
    internal_uuid           STRING      COMMENT 'Canonical customer identifier, known before the call was made',
    received_at             TIMESTAMP   COMMENT 'When we received/wrote this record (near-immediate after the API call)',
    source_generated_at     TIMESTAMP   COMMENT 'Timestamp the fraud provider reports inside the response payload',
    ingest_date             DATE        COMMENT 'Partition column, derived from received_at',
    schema_version          STRING      COMMENT 'Fraud provider response format version',
    raw_payload             STRING      COMMENT 'Entire original JSON payload, untouched, stored as text'
)
PARTITIONED BY (ingest_date)
STORED AS PARQUET
LOCATION 's3://mal-lakehouse/bronze/fraud/'
TBLPROPERTIES ('write.format.default' = 'parquet');

-- Notes:
--   * Because the API call is synchronous and the decision service may act on
--     the in-memory response before this row is durably written, the write
--     path is fire-and-forget via SQS — see etl/ingestion/fraud_sync_client.py.
--   * No matching/validation logic runs here. Cross-validation of the returned
--     phone/email against the internal profile happens in Silver (see
--     sql/silver/silver_fraud_conformed.sql).
